// Offline development artifact; no app imports, API requests or runtime-store access.
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
const base = 'docs/audits/UI_REFACTOR_2026-10-09';
const ledger = JSON.parse(fs.readFileSync(base + '.json', 'utf8'));
const outcomeIds = new Set();
for (const outcome of ledger.progress.outcomes) {
  const finding = ledger.findings.find(item => item.id === outcome.id);
  if (outcomeIds.has(outcome.id) || finding?.status !== 'fixed' ||
      !outcome.verified || !Number.isInteger(outcome.points) || outcome.points !== 10 ||
      !/^[0-9a-f]{40}$/.test(outcome.commit)) {
    throw new Error('Invalid or duplicate committed outcome: ' + outcome.id);
  }
  execFileSync('git', ['merge-base', '--is-ancestor', outcome.commit, 'HEAD'], { stdio: 'pipe', windowsHide: true });
  outcomeIds.add(outcome.id);
}
const data = JSON.stringify(ledger).replaceAll('<', '\\u003c');
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SniperSight · Refactor trail</title>
<style>
:root{color-scheme:light;--bg:oklch(.96 .008 120);--panel:oklch(.99 .004 120);--ink:oklch(.24 .015 125);--muted:oklch(.46 .015 125);--line:oklch(.85 .014 125);--accent:oklch(.43 .09 140);--tint:oklch(.92 .04 140)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 system-ui,sans-serif}button,input{font:inherit}a{color:var(--accent);text-underline-offset:4px}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid var(--accent);outline-offset:4px}
.wrap{max-width:1180px;margin:auto;padding:36px 32px 64px}header{display:flex;gap:24px;justify-content:space-between;align-items:start;border-bottom:1px solid var(--line);padding-bottom:24px}.eyebrow,.mono{font:12px/1.6 ui-monospace,monospace;letter-spacing:.04em}.eyebrow{color:var(--muted)}h1{font-size:34px;letter-spacing:-.04em;line-height:1.15;margin:8px 0 12px}h2{font-size:20px;line-height:1.3;margin:0 0 16px}h3{font-size:16px;margin:0}p{margin:8px 0 16px;max-width:68ch}.intro{color:var(--muted)}.score{text-align:right;min-width:155px;padding-top:8px}.score strong{font-size:28px;font-weight:650;white-space:nowrap}.layout{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:48px;margin-top:32px}.track{height:6px;background:var(--line);border-radius:3px;overflow:hidden;margin:12px 0 8px}.track span{display:block;height:100%;background:var(--accent)}.progress-label{display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:13px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;padding:22px 0 12px}.toolbar button{background:transparent;color:var(--muted);border:1px solid var(--line);border-radius:6px;min-height:44px;padding:8px 14px}.toolbar button[aria-pressed=true]{background:var(--tint);color:var(--accent);border-color:var(--accent)}.level{border-top:1px solid var(--line);padding:18px 0}.level button{display:grid;grid-template-columns:40px minmax(0,1fr) auto;gap:16px;text-align:left;align-items:center;min-height:64px;width:100%;padding:0;border:0;background:transparent;color:var(--ink)}.level button:hover h3{text-decoration:underline;text-underline-offset:4px}.number{font:19px ui-monospace,monospace;color:var(--muted)}.state{font:11px ui-monospace,monospace;border:1px solid var(--line);padding:4px 8px;border-radius:5px}.cleared{color:var(--accent);background:var(--tint);border-color:transparent}.detail{padding:12px 0 0 56px}.detail p{font-size:14px;color:var(--muted)}.detail ul{padding-left:18px;margin:10px 0 16px}.detail li{margin-bottom:8px;font-size:14px}.detail small{display:block;color:var(--muted);font-size:12px}.side{border-left:1px solid var(--line);padding-left:26px}.side section{margin-bottom:28px}.stats{margin:0}.stats div{display:flex;justify-content:space-between;gap:16px;padding:9px 0;border-bottom:1px solid var(--line)}dt{color:var(--muted)}dd{margin:0;font-variant-numeric:tabular-nums}.note{font-size:12px;color:var(--muted)}.milestone{margin:0;padding-left:18px;font-size:14px}.milestone li{margin-bottom:10px}.actions{display:flex;flex-wrap:wrap;gap:12px;font-size:13px}details{border-top:1px solid var(--line);padding:16px 0;margin-top:24px}summary{cursor:pointer;font-weight:600;min-height:44px}.finding{padding:14px 0;border-top:1px solid var(--line)}.finding:first-child{border:0}.finding p{font-size:14px}.finding .mono{color:var(--muted)}footer{margin-top:32px;padding-top:18px;border-top:1px solid var(--line);font-size:12px;color:var(--muted)}[hidden]{display:none!important}
@media(max-width:800px){.layout{grid-template-columns:1fr;gap:28px}.side{border-left:0;padding-left:0;border-top:1px solid var(--line);padding-top:24px}.wrap{padding:24px 20px 44px}.score{min-width:120px}h1{font-size:30px}}
@media(max-width:480px){header{display:block}.score{text-align:left;display:grid;grid-template-columns:1fr auto;gap:4px 12px;padding-top:0}.score .note{grid-column:1/-1}.level button{grid-template-columns:28px minmax(0,1fr);gap:10px}.state{grid-column:2;justify-self:start}.detail{padding-left:38px}.progress-label{flex-wrap:wrap}}
</style></head>
<body><div class="wrap"><header><div><div class="eyebrow">SNIPERSIGHT / DEVELOPMENT / 09 OCT 2026</div><h1>Less noise. More purpose.</h1><p class="intro">A refactor trail with evidence at every checkpoint.</p></div><div class="score"><div class="eyebrow">BLOAT REMOVAL SCORE</div><strong id="score"></strong><div class="note">Verified, committed outcomes only</div></div></header>
<div class="layout"><main><h2>Levels to clear</h2><div class="progress-label"><span id="progress"></span><span>Next: focus the screens</span></div><div class="track" role="progressbar" aria-label="Cleared refactor levels" aria-valuemin="0" id="bar"><span id="fill"></span></div><div class="toolbar" role="group" aria-label="Filter levels"><button aria-pressed="true" data-filter="all">All levels</button><button aria-pressed="false" data-filter="cleared">Cleared</button><button aria-pressed="false" data-filter="planned">Next work</button></div><div id="levels"></div>
<details><summary>Audit findings and remaining work</summary><p class="note">Fixed means the named change was verified. Partial means broader work remains.</p><div id="findings"></div></details></main>
<aside class="side"><section><h2>Evidence, not estimates</h2><dl class="stats" id="stats"></dl><p class="note">Gross removed source is separate from code added for accessibility, tooling and this dashboard.</p></section><section><h2>Clean code milestones</h2><ul class="milestone" id="milestones"></ul></section><section><h2>Score rules</h2><p class="note">10 points per distinct verified, committed finding fixed. A01, A02, A03 and A15 count once each. Related modules, providers and dependencies form one cleanup outcome. Line counts and asset sizes earn no points. The original 70-point checkpoint is preserved in the ledger as historical evidence.</p></section><section><h2>Open the evidence</h2><div class="actions"><a href="UI_REFACTOR_2026-10-09.md">Audit &amp; structure</a><a href="UI_REFACTOR_2026-10-09.json">Task ledger</a><a href="UI_REFACTOR_2026-10-09_removals.json">Removal manifest</a><a href="UI_REFACTOR_2026-10-09_inventory.json">Import inventory</a></div></section></aside></div>
<footer>Saved development checkpoint. Rebuild from the ledger with node scripts/build_refactor_dashboard.mjs. Planned levels are not completed refactors. No runtime connections, trading points or automatic completion awards.</footer></div>
<script type="application/json" id="ledger">${data}</script><script>
const ledger=JSON.parse(document.getElementById('ledger').textContent);
const cleared=ledger.levels.filter(l=>l.status==='cleared').length;
const score=ledger.progress.outcomes.reduce((total,outcome)=>total+outcome.points,0);
document.getElementById('score').textContent=score+' pts';
document.getElementById('progress').textContent=cleared+' of '+ledger.levels.length+' bounded checkpoints cleared';
const bar=document.getElementById('bar');bar.setAttribute('aria-valuemax',ledger.levels.length);bar.setAttribute('aria-valuenow',cleared);document.getElementById('fill').style.width=(cleared/ledger.levels.length*100)+'%';
function element(tag,text,className){const e=document.createElement(tag);if(text)e.textContent=text;if(className)e.className=className;return e;}
function show(filter){const host=document.getElementById('levels');host.replaceChildren();for(const l of ledger.levels.filter(l=>filter==='all'||l.status===filter)){const row=element('article',null,'level');const button=element('button');button.type='button';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','level-'+l.id);button.append(element('span',String(l.id).padStart(2,'0'),'number'),element('h3',l.title),element('span',l.status==='cleared'?'CLEARED':'PLANNED','state '+(l.status==='cleared'?'cleared':'')));const detail=element('div',null,'detail');detail.id='level-'+l.id;detail.hidden=true;detail.append(element('p',l.purpose));const list=element('ul');for(const task of l.tasks)list.append(element('li',task));detail.append(list,element('small','Completion gate: '+l.gate));button.addEventListener('click',()=>{detail.hidden=!detail.hidden;button.setAttribute('aria-expanded',String(!detail.hidden));});row.append(button,detail);host.append(row);}}
show('all');document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));show(button.dataset.filter);}));
const metrics=[['Modules removed',ledger.removals.files],['Source lines removed',ledger.removals.sourceLines],['Root providers retired',ledger.removals.providers],['Direct dependencies removed',ledger.removals.directDependencies.length],['Main entry JS saved',Math.round((ledger.build.before.entryBytes-ledger.build.after.entryBytes)/1000)+' kB'],['Focused tests passed',ledger.verification.frontendTests],['Review candidates retained',ledger.inventory.candidates]];
for(const [label,value]of metrics){const row=element('div');row.append(element('dt',label),element('dd',String(value)));document.getElementById('stats').append(row);}
for(const milestone of ledger.milestones)document.getElementById('milestones').append(element('li',milestone));
for(const finding of ledger.findings){const row=element('div',null,'finding');row.append(element('div',finding.id+' / '+finding.priority+' / '+finding.status,'mono'),element('h3',finding.title),element('p',finding.action));document.getElementById('findings').append(row);}
</script></body></html>`;
fs.writeFileSync(base + '.html', html);
console.log('Dashboard generated: ' + base + '.html');
